/* Generated by Streams Studio: October 18, 2016 at 3:12:58 PM GMT+2 */
package com.ibm.streamsx.metrics;


import java.util.HashMap;
import javax.management.remote.JMXConnectorFactory;
import javax.management.remote.JMXServiceURL;

import org.apache.log4j.Logger;

import com.ibm.streams.operator.AbstractOperator;
import com.ibm.streams.operator.OperatorContext;
import com.ibm.streams.operator.OutputTuple;
import com.ibm.streams.operator.StreamingData.Punctuation;
import com.ibm.streams.operator.StreamingOutput;
import com.ibm.streams.operator.model.Libraries;
import com.ibm.streams.operator.model.OutputPortSet;
import com.ibm.streams.operator.model.OutputPortSet.WindowPunctuationOutputMode;
import com.ibm.streams.operator.model.OutputPorts;
import com.ibm.streams.operator.model.PrimitiveOperator;
import com.ibm.streamsx.metrics.internal.OperatorConfiguration;
import com.ibm.streamsx.metrics.internal.TupleContainer;
import com.ibm.streamsx.metrics.internal.filter.Filters;
import com.ibm.streamsx.metrics.internal.DomainHandler;
import com.ibm.streams.operator.model.Parameter;

/**
 * A source operator that does not receive any input streams and produces new tuples. 
 * The method <code>produceTuples</code> is called to begin submitting tuples.
 * <P>
 * For a source operator, the following event methods from the Operator interface can be called:
 * </p>
 * <ul>
 * <li><code>initialize()</code> to perform operator initialization</li>
 * <li>allPortsReady() notification indicates the operator's ports are ready to process and submit tuples</li> 
 * <li>shutdown() to shutdown the operator. A shutdown request may occur at any time, 
 * such as a request to stop a PE or cancel a job. 
 * Thus the shutdown() may occur while the operator is processing tuples, punctuation marks, 
 * or even during port ready notification.</li>
 * </ul>
 * <p>With the exception of operator initialization, all the other events may occur concurrently with each other, 
 * which lead to these methods being called concurrently by different threads.</p> 
 */
@PrimitiveOperator(
		name="MetricsSource",
		namespace="com.ibm.streamsx.metrics",
		description=MetricsSource.DESC_OPERATOR
		)
@OutputPorts({
	@OutputPortSet(
			cardinality=1,
			optional=false,
			windowPunctuationOutputMode=WindowPunctuationOutputMode.Generating,
			description=MetricsSource.DESC_OUTPUT_PORT
			)
})
@Libraries({
	// As described here:
	// http://www.ibm.com/support/knowledgecenter/en/SSCRJU_4.2.0/com.ibm.streams.dev.doc/doc/jmxapi-start.html
	// Environment variables (@...@) are evaluated during compile-time and must
	// be identical in the run-time environment.
	"@STREAMS_INSTALL@/lib/com.ibm.streams.management.jmxmp.jar",
	"@STREAMS_INSTALL@/lib/com.ibm.streams.management.mx.jar",
	"@STREAMS_INSTALL@/ext/lib/jmxremote_optional.jar"
	})
public class MetricsSource extends AbstractOperator {

	// ------------------------------------------------------------------------
	// Documentation.
	// ------------------------------------------------------------------------
	
	static final String DESC_OPERATOR = 
			"The MetricsSource operator uses the "
			+ "[http://www.ibm.com/support/knowledgecenter/SSCRJU_4.2.0/com.ibm.streams.ref.doc/doc/jmxapi.html|JMX] "
			+ "API to retrieve metrics from one or more jobs, and provides "
			+ "metric changes as tuple stream. Hint: Additional documentation "
			+ "is located in the toolkit description."
			;
	
	protected static final String DESC_OUTPUT_PORT = 
			"The MetricsSource operator emits a metric tuple to this "
			+ "output port for each metric, for which the operator "
			+ "identifies a changed value. You can use the "
			+ "[type:com.ibm.streamsx.metrics::Notification_t|Notification_t] "
			+ "tuple type, or any subset of the attributes specified for this "
			+ "type. After each scan cycle, the operator emits a WindowMarker "
			+ "to this port."
			;
	
	private static final String DESC_PARAM_CONNECTION_URL = 
			"Specifies the connection URL as returned by the `streamtool "
			+ "getjmxconnect` command.";
	
	private static final String DESC_PARAM_USER = 
			"Specifies the user that is required for the JMX connection.";
	
	private static final String DESC_PARAM_PASSWORD = 
			"Specifies the password that is required for the JMX connection.";
	
	private static final String DESC_PARAM_DOMAIN = 
			"Specifies the domain that is monitored.";
	
	private static final String DESC_PARAM_RETRY_PERIOD = 
			"Specifies the period after which a failed JMX connect is retried. "
			+ "The default is 10.0 seconds.";
	
	private static final String DESC_PARAM_RETRY_COUNT = 
			"Specifies the retry count for failed JMX connects. The default is "
			+ "-1, which means infinite retries.";
	
	private static final String DESC_PARAM_FILTER_DOCUMENT = 
			"Specifies the path to a JSON-formatted document that specifies "
			+ "the domain, instance, job, operator, and metric name filters as "
			+ "regular expressions. Each regular expression must follow the "
			+ "rules that are specified for Java "
			+ "[https://docs.oracle.com/javase/7/docs/api/java/util/regex/Pattern.html|Pattern].";
	
	private static final String DESC_PARAM_SCAN_PERIOD = 
			"Specifies the period after which a new metrics scan is "
			+ "initiated. The default is 5.0 seconds.";
	
	// ------------------------------------------------------------------------
	// Implementation.
	// ------------------------------------------------------------------------
	
	/**
	 * Thread for calling <code>produceTuples()</code> to produce tuples 
	 */
	private Thread _processThread;

	/**
	 * Logger for tracing.
	 */
	private static Logger _trace = Logger.getLogger(MetricsSource.class.getName());
	
	private OperatorConfiguration _operatorConfiguration = new OperatorConfiguration();
	
	private DomainHandler _domainHandler = null;
	
	@Parameter(
			optional=false,
			description=MetricsSource.DESC_PARAM_CONNECTION_URL
			)
	public void setConnectionURL(String connectionURL) {
		_operatorConfiguration.set_connectionURL(connectionURL);
	}

	@Parameter(
			optional=false,
			description=MetricsSource.DESC_PARAM_USER
			)
	public void setUser(String user) {
		_operatorConfiguration.set_user(user);
	}

	@Parameter(
			optional=false,
			description=MetricsSource.DESC_PARAM_PASSWORD
			)
	public void setPassword(String password) {
		_operatorConfiguration.set_password(password);
	}

	@Parameter(
			optional=false,
			description=MetricsSource.DESC_PARAM_DOMAIN
			)
	public void setDomain(String domain) {
		_operatorConfiguration.set_domain(domain);
	}

	@Parameter(
			optional=true,
			description=MetricsSource.DESC_PARAM_RETRY_PERIOD
			)
	public void setRetryPeriod(double retryPeriod) {
		_operatorConfiguration.set_retryPeriod(retryPeriod);
	}

	@Parameter(
			optional=true,
			description=MetricsSource.DESC_PARAM_RETRY_COUNT
			)
	public void setRetryCount(int retryCount) {
		_operatorConfiguration.set_retryCount(retryCount);
	}

	@Parameter(
			optional=false,
			description=MetricsSource.DESC_PARAM_FILTER_DOCUMENT
			)
	public void setFilterDocument(String filterDocument) {
		_operatorConfiguration.set_filterDocument(filterDocument);
	}

	@Parameter(
			optional=true,
			description=MetricsSource.DESC_PARAM_SCAN_PERIOD
			)
	public void setScanPeriod(Double scanPeriod) {
		_operatorConfiguration.set_scanPeriod(scanPeriod);
	}

	/**
	 * Initialize this operator. Called once before any tuples are processed.
	 * @param context OperatorContext for this operator.
	 * @throws Exception Operator failure, will cause the enclosing PE to terminate.
	 */
	@Override
	public synchronized void initialize(OperatorContext context)
			throws Exception {
		// Must call super.initialize(context) to correctly setup an operator.
		super.initialize(context);
		Logger.getLogger(this.getClass()).trace("Operator " + context.getName() + " initializing in PE: " + context.getPE().getPEId() + " in Job: " + context.getPE().getJobId() );

		/*
		 * Establish connections or resources to communicate an external system
		 * or data store. The configuration information for this comes from
		 * parameters supplied to the operator invocation, or external
		 * configuration files or a combination of the two. 
		 */

		_operatorConfiguration.set_filters(Filters.setupFilters(_operatorConfiguration.get_filterDocument()));
		boolean isValidDomain = _operatorConfiguration.get_filters().matches(_operatorConfiguration.get_domain());
		if (!isValidDomain)
		{
			throw new com.ibm.streams.operator.DataException("The " + _operatorConfiguration.get_domain() + " domain does not match the specified filter criteria in " + _operatorConfiguration.get_filterDocument());
		}
		
		/*
		 * Prepare the JMX environment settings.
		 */
		HashMap<String, Object> env = new HashMap<String, Object>();
		String [] credentials = { _operatorConfiguration.get_user(), _operatorConfiguration.get_password() };
		env.put("jmx.remote.credentials", credentials);
		env.put("jmx.remote.protocol.provider.pkgs", "com.ibm.streams.management");
		/*
		 * TODO streamtool getdomainproperty jmx.sslOption
		 * Code taken from:
		 * http://www.ibm.com/support/knowledgecenter/en/SSCRJU_4.2.0/com.ibm.streams.dev.doc/doc/jmxapi-lgop.html
		 * 
		 * Is this needed? Seems to be not needed.
		 */
//		String sslOption = "TLSv1";
//		env.put("jmx.remote.tls.enabled.protocols", sslOption);

		/*
		 * Setup the JMX connector and MBean connection.
		 */
		_operatorConfiguration.set_jmxConnector(JMXConnectorFactory.connect(new JMXServiceURL(_operatorConfiguration.get_connectionURL()), env));
		_operatorConfiguration.set_mbeanServerConnection(_operatorConfiguration.get_jmxConnector().getMBeanServerConnection());

		/*
		 * Evaluate the output schema once.
		 * Create and submit tuples to the output port for each changed metric.
		 */
		final StreamingOutput<OutputTuple> port = getOutput(0);
		_operatorConfiguration.set_tupleContainer(new TupleContainer(port));
		
		/*
		 * Further actions are handled in the domain handler that manages
		 * instances that manages jobs, etc.
		 */
		_domainHandler = new DomainHandler(_operatorConfiguration, _operatorConfiguration.get_domain());

		/*
		 * Create the thread for producing tuples. 
		 * The thread is created at initialize time but started.
		 * The thread will be started by allPortsReady().
		 */
		_processThread = getOperatorContext().getThreadFactory().newThread(
				new Runnable() {

					@Override
					public void run() {
						try {
							produceTuples();
						} catch (Exception e) {
							Logger.getLogger(this.getClass()).error("Operator error", e);
						}                    
					}

				});

		/*
		 * Set the thread not to be a daemon to ensure that the SPL runtime
		 * will wait for the thread to complete before determining the
		 * operator is complete.
		 */
		_processThread.setDaemon(false);
	}

	/**
	 * Notification that initialization is complete and all input and output ports 
	 * are connected and ready to receive and submit tuples.
	 * @throws Exception Operator failure, will cause the enclosing PE to terminate.
	 */
	@Override
	public synchronized void allPortsReady() throws Exception {
		OperatorContext context = getOperatorContext();
		Logger.getLogger(this.getClass()).trace("Operator " + context.getName() + " all ports are ready in PE: " + context.getPE().getPEId() + " in Job: " + context.getPE().getJobId() );
		// Start a thread for producing tuples because operator 
		// implementations must not block and must return control to the caller.
		_processThread.start();
	}

	/**
	 * Submit new tuples to the output stream
	 * @throws Exception if an error occurs while submitting a tuple
	 */
	private void produceTuples() throws Exception  {
		boolean quit = false;
		while(!quit) {
			_domainHandler.captureMetrics();
			
			/*
			 * Emit a window marker after each scan cycle.
			 */
			_operatorConfiguration.get_tupleContainer().punctuate(Punctuation.WINDOW_MARKER);

			Thread.sleep(Double.valueOf(_operatorConfiguration.get_scanPeriod() * 1000.0).longValue());
		}

		/*
		 * When finished, submit a final punctuation:
		 */
		_operatorConfiguration.get_tupleContainer().punctuate(Punctuation.FINAL_MARKER);
	}

	/**
	 * Shutdown this operator, which will interrupt the thread
	 * executing the <code>produceTuples()</code> method.
	 * @throws Exception Operator failure, will cause the enclosing PE to terminate.
	 */
	public synchronized void shutdown() throws Exception {
		if (_processThread != null) {
			_processThread.interrupt();
			_processThread = null;
		}
		OperatorContext context = getOperatorContext();
		Logger.getLogger(this.getClass()).trace("Operator " + context.getName() + " shutting down in PE: " + context.getPE().getPEId() + " in Job: " + context.getPE().getJobId() );

		// Close connections or release resources related to any external system or data store.
		
		if (_operatorConfiguration.get_jmxConnector() != null) {
			_operatorConfiguration.get_jmxConnector().close();
		}

		// Must call super.shutdown()
		super.shutdown();
	}
}
